### ISSUE TITLE
Die Viescher sind nicht draußen!

### ISSUE THREAD

**Issue by LinuxlasGNUleaf** [HackathonGermany/Smart#1]
**Issue:** Viescher nicht draußen
**How to reproduce:** Moch doch die Äugen öuf! De Viescher send ned draußä!

**Comment by ColdFireHunter** [comment]
Ohh das erste Issue.

**Comment by LinuxlasGNUleaf** [comment]
Hast du das Issue denn behoben? Ich seh nämlich keine Commits...
